#---------------------------------------------------------------------
# Falls dir ein paar Sachen nicht gefallen, kannst du sie hier ändern.
#---------------------------------------------------------------------

# Der Prefix des Plugins
 Prefix: '&6»&9Smash&6 | &7'