name: Smash
author: Todfresser
version: 1.0
api-version: 1.16
main: todfresser.smash.main.Smash
commands:
  smash:
    description: Zeigt dir alle Befehle von Smash.
    usage:
    aliases: sm
  sound:
    description: Spielt einen Sound.
    usage: |
       /sound
       Example: /sound [SoundName] [volume] [pitch]
       Example: /sound [SoundName]
  particle:
    description: Zeigt einen ParticleEffect.
    usage: |
       /particle
       Example: /particle [EffectName] [offsetX] [offsetY] [offsetZ] [speed] [amount]
       Example: /particle [EffectName]
permissions:
  SMASH.*:
    description: Gibt Zugriff auf alle Befehle.
    children:
      SMASH.admin: true
      SMASH.basic: true
  SMASH.admin:
    description: Erlaubt dir ein Spiel zu erstellen.
    default: op
  SMASH.basic:
    description: Gibt dir die Grund-Rechte.
    default: true